version: '3'

services:
  # Not working
  # web:
  #   build:
  #     context: .
  #     dockerfile: ./docker/app.dockerfile
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - .:/simple-go-mysql
  #   depends_on:
  #     - database
  #   container_name: simple-go-mysql-web
  #   environment:
  #     - 'DB_PORT=3306'
  #     - 'DB_HOST=database'

  database:
    build: 
      context: .
      dockerfile: ./docker/db.dockerfile
    environment:
      #MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: simple-go-mysql
    container_name: simple-go-mysql-db
    ports:
      - 3306:3306
    volumes:
      - simple-go-mysql-data:/var/lib/mysql 

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 5003:80
    environment:
      - 'PMA_HOST=database'
      - 'PMA_PORT=3306'
    container_name: simple-go-mysql-pma


# persisted storage
volumes:
  simple-go-mysql-data: